theme = "catppuccin_mocha"

[editor]
auto-pairs = false
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
cursorline = true
line-number = "relative"
color-modes = true
scrolloff = 10

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
